name: WIP
# You may pin to the exact commit or the version.
# uses: wip/action@032daff62a8e89e075c7824b4ac296cb0eb4612e
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
uses: wip/action@v1.1.0
